### ISSUE TITLE
Missing uthash/src/uthash.h

### ISSUE THREAD

**Issue by breedx2** [residuum/PuRestJson#37]
Master won't compile because
`json-encode.c` line 36 says:

```
#include "uthash/src/uthash.h"
```

but this file is not included in the github repository.

**Comment by breedx2** [comment]
I guess uthash should be called out as an external dependency, or else the files should be included with this project.  I worked around this by installing the system package `uthash-dev` and changing the include in two files to `<uthash.h>`.

See this gist:
https://gist.github.com/breedx2/b86075d810dcad26ccf0

**Comment by residuum** [comment]
You need to update the submodule: 

    git submodule update --init

**Comment by breedx2** [comment]
Hey, thanks for pointing that out!  It never even occurred to me that it might be a git submodule (I so rarely use those!).

Maybe a comment/update to the wiki could help here...but thanks again.

**Comment by residuum** [comment]
I have upated the wiki with lots of new information, including the compilation using uthash.

**Comment by breedx2** [comment]
Super!  Thanks for following up.
