### ISSUE TITLE
please remove debian/ directory

### ISSUE THREAD

**Issue by umlaeute** [residuum/PuRestJson#40]
i'm currently uploaded a 'pd-purest-json' package to Debian.

as explained in [Debian's Upstream Guide](https://wiki.debian.org/UpstreamGuide), I would like to ask you to remove the `debian/` packaging directory from the repository, as it will become obsolete once the package is in Debian.

(you are of course welcome to only remove it, once the package has entered Debian; e.g. before your next release).

**Comment by residuum** [comment]
Thank you for packaging.

One Thing: I am currently making the switch from the library template to pd-lib-builder. I am just ironing out some things in a branch (new-build). I am not sure, if modifying the build process using the current Makefile is worth it.
