### ISSUE TITLE
Large JSON file crashes encode/decode

### ISSUE THREAD

**Issue by nyboer** [residuum/PuRestJson#43]
Working on an ARM7 computer (NTC CHIP) running a debian 4.3 kernel. 
I opened this file with json_encode and tried to decode it. PD 046-7 crashes. Yes, it's quite big, as far as JSON files go. Using purest json installed with apt-get from stretch repo. 

[sis.txt](https://github.com/residuum/PuRestJson/files/253175/sis.txt)
![patchimg](https://cloud.githubusercontent.com/assets/13511493/15088358/607899b8-13a7-11e6-88fd-02b695a91da2.png)

**Comment by residuum** [comment]
json-encode does not crash on my desktop machine with that file, but I will try to reproduce your problem, maybe it will crash on my Raspberry Pi or I will have to generate a larger file.

**Comment by nyboer** [comment]
Yes, it seems to be a problem on the 2nd click. If I click it once, it seems to do nothing, if I click it again, it crashes pd with an error like:
```
*** Error in `pd': free(): invalid pointer: 0x000ed7cf ***
```
Also, I tried to hang a "print" object off the end of that [t a a]. PD hangs, and I got
```
 *** Error in `pd': corrupted double-linked list: 0x000ed878 ***
```
in the terminal.  Can't consistently reproduce that, though.

**Comment by residuum** [comment]
Two things:

1. `[read(` on `[json-encode]` does not output anything, it only loads the content of the file. To output the stored JSON, use `[bang(`.
1. I am still struggling with debugging the object, but I am at it.

**Comment by residuum** [comment]
OK, I have already had the same issue with `[json-decode]`. Time to make a sample application in C and report the bug to json-c:

This segfaults:
https://github.com/residuum/PuRestJson/blob/69a265a9bb6b24a4f1703b6e3a54c9bb5e550c86/src/json-encode.c#L194

This is the segfault in `[json-decode]`:
https://github.com/residuum/PuRestJson/blob/69a265a9bb6b24a4f1703b6e3a54c9bb5e550c86/src/json-decode.c#L155

Similar issue reported to json-c
https://github.com/json-c/json-c/issues/158
