### ISSUE TITLE
can't create [json-decode]/[json-encode]

### ISSUE THREAD

**Issue by umlaeute** [residuum/PuRestJson#52]
i stumbled across the "same" thing as #51 with the Debian package (which i maintain :woman_facepalming: ) of PuRestJson.
Here the issue seems to be that `json-decode` and `json-encode` use `is_error`, which is an undefined symbol with json-c >=0.13 (actually it's a `define` in `json-c/bits.h`, but this file is never included by PuRestJson)

all the other objects from this library seem to work fine.

I've created a new ticket even though this might be a dupe of #51, just in case (my problem is on Debian; and Debian only switched to json-c_0.13 in mid-2018)

**Comment by residuum** [comment]
I am in the process of releasing a new version, but I have a problem with compilation for Windows.

**Comment by umlaeute** [comment]
closing this, as it was apparently fixed with 9f2d1877db88ffbc1a7e403de5fa3e207bdaed39
