### ISSUE TITLE
[oauth] 1.4.3 not working on windows10

### ISSUE THREAD

**Issue by 60-hz** [residuum/PuRestJson#58]
Windows10, pd-0.51-0 64bit  and PuRestJson 1.4.3:

a POST or a GET message to [oauth] always return this error:

"Unspecified error while performing request (network disconnect?)."

**Edit:** Same computer, I could make it work nicely with pd-0.51-0 32bit and PuRestJson 1.4.2 32bit from deken package. So this version is also compatible with Purr Data since it is still 32bit on windows...

**Comment by residuum** [comment]
There are no 64 bit packages available for now, it may change in the future.
