### ISSUE TITLE
[oauth] problem in OSX

### ISSUE THREAD

**Issue by 60-hz** [residuum/PuRestJson#59]
After a correct "Init" message, a "GET" works one time out of ten... when it works, any further GET returns:

Error while performing request: Problem with the SSL CA cert (path? access rights?)
status2:  77 Problem\ with\ the\ SSL\ CA\ cert\ (path?\ access\ rights?)

Tested with twitter example, same patch works perfectly on Linux.

pd-0.51-1
OSX 10.15.4
PuRest v1.4.3 from Deken

**Comment by residuum** [comment]
Does this help? https://github.com/residuum/PuRestJson/issues/67#issuecomment-1307993667

**Comment by 60-hz** [comment]
I tested with pd-0.53 with MacOS Monterey. Both work, but:
build 136: need to uncheck SSL (sslcheck 0)
build 194:  SSL check or uncheck works

**Comment by residuum** [comment]
Thanks.
