### ISSUE TITLE
error: implicit declaration of function 'error' is invalid in C99

### ISSUE THREAD

**Issue by ivan-ef** [residuum/PuRestJson#68]
when compiling on intel Mac:

In file included from src/json-encode.c:38:
src/inc/kvp.c:160:2: error: implicit declaration of function 'error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        MYASSERT(kvp->is_array != 1 || is_array != 1, "This should not be called: array values should be appended, not replaced.");
        ^
src/purest_json.h:47:9: note: expanded from macro 'MYASSERT'
        MYERROR(__VA_ARGS__);    \
        ^
src/purest_json.h:35:23: note: expanded from macro 'MYERROR'
        #define MYERROR(...) error(__VA_ARGS__)
                             ^
src/json-encode.c:134:5: error: implicit declaration of function 'error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                MYERROR("What other JSON type?");
                                ^
src/purest_json.h:35:23: note: expanded from macro 'MYERROR'
        #define MYERROR(...) error(__VA_ARGS__)
                             ^
6 errors generated.
make: *** [src/json-encode.o] Error 1

**Comment by residuum** [comment]
What source version are you using? The macro MYERROR() has been removed and replaced by pd_error() with https://github.com/residuum/PuRestJson/commit/d8591fc5d29286d0b18c88e0096dc61111f1a2af

**Comment by ivan-ef** [comment]
My mistake, vas 1.4.3 from releases.

**Comment by ivan-ef** [comment]
could you help with this error?

rc/oauth.h:31:10: error: 'oauth.h' file not found with <angled> include; use "quotes" instead
#include <oauth.h>
         ^~~~~~~~~
         "oauth.h"

**Comment by residuum** [comment]
That is something I am trying to figure out, i.e. the whole packaging process. That would then yield a new release, but I have made no real progress since June.

One step would be to use the code from pd-lib-builder: https://git.iem.at/pd/iem-ci/-/tree/main/pd-lib-builder

But linking dependencies on Mac M1 is still unsolved for me: https://lists.puredata.info/pipermail/pd-dev/2022-06/thread.html#23088

**Comment by ivan-ef** [comment]
I glad to help, but I'm very newbie to C. 
when I compiling looks like it searches in directories pre-designated by the compiler, but can't find my dependancies installed by homebrew. So I had to manually add required libs to main folder and change #include < > to " ". I guess something still missing.

**Comment by patricecolet** [comment]
it's in /opt/homebrew

Compilation on m1 is resolved here:

https://github.com/residuum/PuRestJson/issues/69#issue-1437146159
