### ISSUE TITLE
Cannot open [rest] and [oauth] on Mac

### ISSUE THREAD

**Issue by tomastik** [residuum/PuRestJson#76]
Hello, I eagerly installed the new version 2.0.0 using Deken on Pure Data 0.53. Seems like two objects are unusable/unavailable.  For example, trying to open [rest] gives this on the Pd console:

/Users/X/Documents/Pd/externals/purest_json/rest.pd_darwin: dlopen(/Users/X/Documents/Pd/externals/purest_json/rest.pd_darwin, 10): Symbol not found: _curl_multi_poll
  Referenced from: /Users/an/Documents/Pd/externals/purest_json/rest.pd_darwin

I am on Macbook Pro Intel i7, Big Sur 11.6.7

Thanks,
Antonio

**Comment by residuum** [comment]
Looking at the compilation code, I see a message: https://app.circleci.com/pipelines/github/residuum/PuRestJson/54/workflows/3891b2c3-797b-487b-8b3e-a92bf3526b32/jobs/316?invite=true#step-102-128

It looks like curl is not installed by default, but on the compilation machine at Circle CI.

**Comment by residuum** [comment]
Could you test the latest build? https://cloud.residuum.org/index.php/s/380C60JAabnO7jk/download?path=%2F&files=318_2022-11-29_purest_json%5Bv2.0.0%5D(Darwin-amd64-32)(Darwin-arm64-32).dek

.dek files are just renamed zip files, so you should be able to open the files and then copy those to overwrite the other files.

**Comment by tomastik** [comment]
Works for me now! Wonderful, thanks.
